Repository WildCodeSchool/orleans-0218-labo, pull requests merged in 2018-06, with the labels that each got.

#58 fixtures pour table room
  app/AppKernel.php
  composer.json
  composer.lock
  package-lock.json
  package.json
  src/AppBundle/DataFixtures/AppFixtures.php
Labels: change requested, correction done

#64 Dev
  .gitignore
  app/AppKernel.php
  app/Resources/views/admin/room/edit.html.twig
  app/Resources/views/admin/room/index.html.twig
  composer.json
  composer.lock
  package-lock.json
  package.json
  src/AppBundle/Controller/AdminRoomController.php
  src/AppBundle/DataFixtures/AppFixtures.php
  src/AppBundle/Form/RoomType.php
Labels: reviewed by PO

#62 S2 us48 acces aux différentes pages admin depuis accueil
  app/Resources/views/admin/equipment/edit.html.twig
  app/Resources/views/admin/equipment/index.html.twig
  app/Resources/views/admin/equipment/new.html.twig
  app/Resources/views/admin/equipment/show.html.twig
  app/Resources/views/admin/layoutAdmin.html.twig
  app/Resources/views/admin/navbar.html.twig
  app/Resources/views/admin/room/edit.html.twig
  app/Resources/views/admin/room/index.html.twig
  app/Resources/views/admin/room/new.html.twig
  app/Resources/views/admin/staff/edit.html.twig
  app/Resources/views/admin/staff/index.html.twig
  app/Resources/views/admin/staff/new.html.twig
  app/Resources/views/admin/staff/show.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/default/index.html.twig
  app/Resources/views/layoutMain.html.twig
  app/Resources/views/navbar.html.twig
  assets/js/app.js
  assets/scss/main.scss
  package-lock.json
  package.json
  webpack.config.js
Labels: reviewed by PO

#85 Fix equip fixturs
  .gitignore
  app/Resources/views/admin/equipment/edit.html.twig
  app/Resources/views/admin/equipment/index.html.twig
  app/Resources/views/admin/equipment/new.html.twig
  app/Resources/views/admin/navbar.html.twig
  app/Resources/views/admin/staff/new.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/default/index.html.twig
  composer.lock
  src/AppBundle/Command/HtmlValidatorCommand.php
  src/AppBundle/Controller/EquipmentController.php
  src/AppBundle/DataFixtures/AppFixtures.php
  var/reports/.gitkeep
Labels: reviewed by PO

#88 Dev
  app/Resources/views/admin/equipment/edit.html.twig
  app/Resources/views/admin/equipment/index.html.twig
  app/Resources/views/admin/equipment/new.html.twig
  app/Resources/views/admin/equipment/show.html.twig
  app/Resources/views/admin/layoutAdmin.html.twig
  app/Resources/views/admin/navbar.html.twig
  app/Resources/views/admin/room/edit.html.twig
  app/Resources/views/admin/room/index.html.twig
  app/Resources/views/admin/room/new.html.twig
  app/Resources/views/admin/staff/edit.html.twig
  app/Resources/views/admin/staff/index.html.twig
  app/Resources/views/admin/staff/new.html.twig
  app/Resources/views/admin/staff/show.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/default/index.html.twig
  app/Resources/views/layoutMain.html.twig
  app/Resources/views/navbar.html.twig
  app/Resources/views/reservation/new.html.twig
  assets/js/app.js
  assets/scss/main.scss
  composer.lock
  package-lock.json
  package.json
  src/AppBundle/Controller/EquipmentController.php
  src/AppBundle/Controller/ReservationController.php
  src/AppBundle/Controller/StaffController.php
  src/AppBundle/DataFixtures/AppFixtures.php
  webpack.config.js
Labels: reviewed by PO

#92 S3 us50 show equipment
  app/Resources/views/admin/equipment/index.html.twig
  app/Resources/views/admin/equipment/show.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/EquipmentController.php
  src/AppBundle/DataFixtures/AppFixtures.php
Labels: reviewed by PO

#94 Fix home page from client review
  app/Resources/views/default/index.html.twig
  app/Resources/views/navbar.html.twig
  assets/scss/main.scss
  web/images/Logo_LABO_Home.png
  web/images/Logo_LABO_V2_NoirQuadri.png
  web/images/orleans_pepinieres.png
Labels: reviewed by PO

#95 CSS var done
  app/Resources/views/default/index.html.twig
  app/Resources/views/navbar.html.twig
  assets/scss/main.scss
  web/images/logo labo_blanc.png
Labels: reviewed by PO

#101 Test
  tests/AppBundle/Controller/DefaultControllerTest.php
Labels: reviewed by PO

#107 Création section réservation client
  app/Resources/views/reservation/new.html.twig
  src/AppBundle/Controller/ReservationController.php
  src/AppBundle/DataFixtures/AppFixtures.php
  src/AppBundle/Entity/Reservation.php
  src/AppBundle/Form/ReservationType.php
Labels: reviewed by PO

#111 Dev
  app/Resources/views/admin/equipment/index.html.twig
  app/Resources/views/admin/equipment/show.html.twig
  app/Resources/views/default/index.html.twig
  app/Resources/views/navbar.html.twig
  app/Resources/views/reservation/new.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/EquipmentController.php
  src/AppBundle/Controller/ReservationController.php
  src/AppBundle/DataFixtures/AppFixtures.php
  src/AppBundle/Entity/Reservation.php
  src/AppBundle/Form/ReservationType.php
  tests/AppBundle/Controller/DefaultControllerTest.php
  web/images/Logo_LABO_Home.png
  web/images/Logo_LABO_V2_NoirQuadri.png
  web/images/logo labo_blanc.png
  web/images/orleans_pepinieres.png
Labels: reviewed by PO

#115 Nettoyage du scss
  assets/scss/admin.scss
  assets/scss/home.scss
  assets/scss/main.scss
  assets/scss/variables.scss
Labels: reviewed by PO

#122 S5 us46 equipment priority
  app/Resources/views/admin/equipment/index.html.twig
  app/Resources/views/admin/equipment/new.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/EquipmentController.php
  src/AppBundle/Entity/Equipment.php
  src/AppBundle/Form/EquipmentType.php
  src/AppBundle/Service/OrderService.php
Labels: reviewed by PO

#128 S5 us49 vich add picture
  .travis.yml
  app/AppKernel.php
  app/config/config.yml
  composer.json
  composer.lock
  src/AppBundle/Entity/Equipment.php
  src/AppBundle/Form/EquipmentType.php
  web/images/products/.gitkeep
Labels: reviewed by PO

#130 fix probleme scss avec catamaran
  assets/scss/home.scss
  assets/scss/main.scss
Labels: reviewed by PO

#127 Reservation v3
  app/Resources/views/admin/equipment/edit.html.twig
  app/Resources/views/admin/equipment/new.html.twig
  app/Resources/views/admin/navbar.html.twig
  app/Resources/views/admin/room/edit.html.twig
  app/Resources/views/admin/room/new.html.twig
  app/Resources/views/admin/staff/edit.html.twig
  app/Resources/views/admin/staff/new.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/default/index.html.twig
  app/Resources/views/navbar.html.twig
  app/Resources/views/reservation/index.html.twig
  app/Resources/views/reservation/new.html.twig
  app/Resources/views/reservation/show.html.twig
  assets/js/reservation.js
  assets/scss/home.scss
  assets/scss/main.scss
  package-lock.json
  package.json
  src/AppBundle/Controller/ReservationController.php
  src/AppBundle/Controller/ReservationEquipmentController.php
  src/AppBundle/DataFixtures/AppFixtures.php
  src/AppBundle/Entity/Equipment.php
  src/AppBundle/Entity/Reservation.php
  src/AppBundle/Entity/ReservationEquipment.php
  src/AppBundle/Form/ReservationEquipmentType.php
  src/AppBundle/Form/ReservationType.php
  src/AppBundle/Repository/ReservationEquipmentRepository.php
  src/AppBundle/Service/OrderService.php
  src/AppBundle/Tests/Controller/ReservationEquipmentControllerTest.php
  web/images/arrow-circle-left.svg
  web/images/bg1.png
  web/images/cog.svg
  webpack.config.js
Labels: reviewed by PO

#148 link to back to homepage, updatedate nullable, type done for reservat…
  app/Resources/views/navbar.html.twig
  src/AppBundle/Controller/ReservationController.php
  src/AppBundle/Entity/Equipment.php
  src/AppBundle/Entity/ReservationEquipment.php
Labels: reviewed by PO

#149 Fix arrow
  app/Resources/views/admin/equipment/index.html.twig
  web/images/angle-down.svg
  web/images/angle-up.svg
Labels: reviewed by PO

#147 OrderService devient générique
  app/Resources/views/admin/equipment/index.html.twig
  assets/scss/admin.scss
  assets/scss/main.scss
  src/AppBundle/Controller/EquipmentController.php
  src/AppBundle/Entity/Equipment.php
  src/AppBundle/Entity/OrderInterface.php
  src/AppBundle/Service/OrderService.php
Labels: reviewed by PO

#152 fix resa
  app/Resources/views/admin/equipment/show.html.twig
  app/Resources/views/reservation/index.html.twig
  app/Resources/views/reservation/new.html.twig
  assets/scss/home.scss
  assets/scss/main.scss
  assets/scss/variables.scss
Labels: reviewed by PO

#154 Fix equipment order
  src/AppBundle/Controller/ReservationController.php
  src/AppBundle/DataFixtures/AppFixtures.php
  src/AppBundle/Entity/Equipment.php
Labels: reviewed by PO

#156 Edit done, IntergerType for quantity-field, routing done, Fixtures OK…
  app/Resources/views/reservation/edit.html.twig
  app/Resources/views/reservation/index.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/ReservationController.php
  src/AppBundle/DataFixtures/AppFixtures.php
  src/AppBundle/Entity/Equipment.php
  src/AppBundle/Form/ReservationEquipmentType.php
Labels: reviewed by PO

#153 fix de la home page
  app/Resources/views/default/index.html.twig
  app/Resources/views/navbar.html.twig
  assets/scss/home.scss
  assets/scss/main.scss
  package-lock.json
Labels: conflicts

#158 fix scss
  app/Resources/views/navbar.html.twig
  app/Resources/views/reservation/new.html.twig
  assets/scss/home.scss
  assets/scss/main.scss
  assets/scss/variables.scss
Labels: reviewed by PO

#159 fix des problemes de div equipement
  assets/scss/main.scss
Labels: reviewed by PO

#160 Dev to master ENFIN
  .travis.yml
  app/AppKernel.php
  app/Resources/views/admin/equipment/edit.html.twig
  app/Resources/views/admin/equipment/index.html.twig
  app/Resources/views/admin/equipment/new.html.twig
  app/Resources/views/admin/equipment/show.html.twig
  app/Resources/views/admin/navbar.html.twig
  app/Resources/views/admin/room/edit.html.twig
  app/Resources/views/admin/room/new.html.twig
  app/Resources/views/admin/staff/edit.html.twig
  app/Resources/views/admin/staff/new.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/default/index.html.twig
  app/Resources/views/navbar.html.twig
  app/Resources/views/reservation/edit.html.twig
  app/Resources/views/reservation/index.html.twig
  app/Resources/views/reservation/new.html.twig
  app/Resources/views/reservation/show.html.twig
  app/config/config.yml
  assets/js/reservation.js
  assets/scss/admin.scss
  assets/scss/home.scss
  assets/scss/main.scss
  assets/scss/variables.scss
  composer.json
  composer.lock
  package-lock.json
  package.json
  src/AppBundle/Controller/EquipmentController.php
  src/AppBundle/Controller/ReservationController.php
  src/AppBundle/Controller/ReservationEquipmentController.php
  src/AppBundle/DataFixtures/AppFixtures.php
  src/AppBundle/Entity/Equipment.php
  src/AppBundle/Entity/OrderInterface.php
  src/AppBundle/Entity/Reservation.php
  src/AppBundle/Entity/ReservationEquipment.php
  src/AppBundle/Form/EquipmentType.php
  src/AppBundle/Form/ReservationEquipmentType.php
  src/AppBundle/Form/ReservationType.php
  src/AppBundle/Repository/ReservationEquipmentRepository.php
  src/AppBundle/Service/OrderService.php
  src/AppBundle/Tests/Controller/ReservationEquipmentControllerTest.php
  web/images/angle-down.svg
  web/images/angle-up.svg
  web/images/arrow-circle-left.svg
  web/images/bg1.png
  web/images/cog.svg
  web/images/products/.gitkeep
  webpack.config.js
Labels: reviewed by PO

#163 S6 us50 staff order
  app/Resources/views/admin/staff/index.html.twig
  app/Resources/views/admin/staff/show.html.twig
  src/AppBundle/Controller/StaffController.php
  src/AppBundle/DataFixtures/AppFixtures.php
  src/AppBundle/Entity/Staff.php
Labels: reviewed by PO

#165 Us52 scrollequipment
  app/Resources/views/reservation/new.html.twig
  assets/scss/main.scss
Labels: reviewed by PO

#167 S6 us06 reservation room
  app/Resources/views/form/fields.html.twig
  app/Resources/views/reservation/new.html.twig
  assets/js/reservation.js
  assets/scss/main.scss
  src/AppBundle/DataFixtures/AppFixtures.php
  src/AppBundle/Entity/Reservation.php
  src/AppBundle/Form/ReservationType.php
Labels: reviewed by PO

#164 S6 us35 delete reservation
  app/Resources/views/admin/equipment/index.html.twig
  app/Resources/views/reservation/index.html.twig
  src/AppBundle/Controller/EquipmentController.php
  src/AppBundle/Controller/ReservationController.php
  src/AppBundle/Entity/Reservation.php
Labels: reviewed by PO

#168 fix
  app/Resources/views/admin/equipment/show.html.twig
  assets/scss/main.scss
Labels: reviewed by PO

#169 fix
  app/Resources/views/admin/equipment/edit.html.twig
  app/Resources/views/admin/equipment/new.html.twig
  app/Resources/views/admin/room/new.html.twig
  app/Resources/views/admin/staff/edit.html.twig
  app/Resources/views/admin/staff/new.html.twig
  app/Resources/views/reservation/new.html.twig
  assets/scss/main.scss
Labels: reviewed by PO

#170 Error done for Equipment/room/staff's parts - Room done for the edit …
  app/Resources/views/admin/equipment/index.html.twig
  app/Resources/views/admin/room/index.html.twig
  app/Resources/views/admin/staff/index.html.twig
  app/Resources/views/reservation/edit.html.twig
  app/Resources/views/reservation/new.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/AdminRoomController.php
  src/AppBundle/Controller/EquipmentController.php
  src/AppBundle/Controller/StaffController.php
Labels: reviewed by PO

#174 fix
  src/AppBundle/DataFixtures/AppFixtures.php
Labels: reviewed by PO

#175 Fixes button admin fixed bottom
  app/Resources/views/admin/equipment/index.html.twig
  app/Resources/views/admin/room/index.html.twig
  app/Resources/views/admin/staff/index.html.twig
  app/Resources/views/reservation/index.html.twig
  assets/scss/admin.scss
Labels: reviewed by PO

#176 Recapitulatif d'une réservation
  app/Resources/views/reservation/show.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/ReservationController.php
  web/images/check-circle.svg
Labels: reviewed by PO

#177 Fix done
  app/Resources/views/admin/equipment/index.html.twig
  app/Resources/views/admin/room/index.html.twig
  app/Resources/views/admin/staff/index.html.twig
  app/Resources/views/reservation/edit.html.twig
  assets/scss/admin.scss
Labels: reviewed by PO

#179 Fix_order
  app/Resources/views/admin/equipment/index.html.twig
  app/Resources/views/admin/staff/index.html.twig
  app/Resources/views/reservation/show.html.twig
  src/AppBundle/Controller/EquipmentController.php
  src/AppBundle/Controller/StaffController.php
Labels: reviewed by PO

#181 Dev to master
  app/Resources/views/admin/equipment/index.html.twig
  app/Resources/views/admin/staff/index.html.twig
  app/Resources/views/reservation/show.html.twig
  src/AppBundle/Controller/EquipmentController.php
  src/AppBundle/Controller/StaffController.php
Labels: reviewed by PO
